version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Bannerlord.Module.CSharp/"
    schedule:
      interval: "daily"
      
