version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/Bannerlord.Module.CSharp/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Newtonsoft.Json"
      - dependency-name: "Bannerlord.ReferenceAssemblies.*"
      - dependency-name: "Lib.Harmony"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
